### PR TITLE
converting 'THIS_STYLE' redux action types to camel case 'thisStyle' …

### PR DESCRIPTION
**Pull request by bipvanwinkle**
…to match elm convention

### CODE REVIEW

**Comment by stoeffel** [comment]
looks good. Could you also update the example? Currently it uses lowercased action types.

**Comment by bipvanwinkle** [comment]
Will do

**Comment by bipvanwinkle** [comment]
I think the example uses the right style of action types now. Wanna make sure I didn't miss something?

**Comment by stoeffel** [comment]
LGTM. Thanks a lot! I will publish later this evening.

**Comment by stoeffel** [comment]
published v1.1.0

// cc @Bipsy

**Pull request merged**
